app = "voice-to-text-bot"
primary_region = "ams"

[build]
  image = "ghcr.io/n0th1ng-else/voice-to-text-bot/voice-to-speech-app:latest"

[mounts]
  source = "voice-to-text-bot__data"
  destination = "/app/data"
  processes = ["disk", "app"]
  initial_size = "1gb"