apiVersion: apps/v1
kind: Deployment
metadata:
  name: voice-to-speech
  labels:
    app: voice-to-speech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voice-to-speech
  template:
    metadata:
      labels:
        app: voice-to-speech
    spec:
      containers:
        - image: "docker.pkg.github.com/n0th1ng-else/voice-to-text-bot/voice-to-speech-app:latest"
          imagePullPolicy: Always
          name: voice-to-speech
          ports:
            - name: app-port
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 180
            periodSeconds: 30
            failureThreshold: 10
            tcpSocket:
              port: app-port
          readinessProbe:
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 10
            httpGet:
              path: /health
              port: app-port
