name: Install NodeJS and NPM modules

runs:
  using: "composite"
  steps:
    - name: Setup NodeJS using the obtained nvm version
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version-file: ".nvmrc"

    - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
      with:
        version: 9
        run_install: |
          args: [--frozen-lockfile]
