name: Install NodeJS and NPM modules

runs:
  using: "composite"
  steps:
    - name: Setup NodeJS using the obtained nvm version
      uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"

    - uses: pnpm/action-setup@v4
      with:
        version: 9
        run_install: |
          args: [--frozen-lockfile]
