name: Install NodeJS and NPM modules

runs:
  using: "composite"
  steps:
    - name: Setup NodeJS using the obtained nvm version
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version-file: ".nvmrc"

    - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      with:
        version: 9
        run_install: |
          args: [--frozen-lockfile]
