name: Main CI

on:
  push:
    branches:
      - master

jobs:
  scan:
    uses: ./.github/workflows/scan.yml
    secrets: inherit

  prerelease:
    needs: [scan]
    uses: ./.github/workflows/prerelease.yml
    secrets: inherit

  deploy:
    needs: [prerelease]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      version: ${{ needs.prerelease.outputs.version }}
      sha: ${{ github.sha }}
      # Enable if you want to test on one environment
      # servers: '["Production Î²"]'
