name: PR CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  scan:
    uses: ./.github/workflows/scan.yml
    secrets: inherit

  build:
    needs: [scan]
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      version: v0.0.0-${{ github.event.pull_request.head.sha }}
      sha: ${{ github.event.pull_request.head.sha }}
