name: App Deploy

on:
  workflow_call:
    inputs:
      servers:
        type: string
        description: "The JSON list of servers to deploy the application"
        default: '["Production β", "Production Ω"]'
        # Will deploy into all available servers if not specified
        required: false
      version:
        type: string
        description: "Version tag (ie v1.0.0)"
        required: true
      sha:
        type: string
        description: "Commit sha"
        required: true

jobs:
  build:
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      docker-tag: latest
      version: ${{ inputs.version }}
      sha: ${{ inputs.sha }}

  release:
    uses: ./.github/workflows/heroku.yml
    secrets: inherit
    with:
      version: ${{ inputs.version }}
      servers: ${{ inputs.servers }}
