name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      server:
        type: choice
        options:
          - "Production Î©"
          - "Production Î²"
        description: "What server to deploy the application on"
        required: true
      version:
        type: string
        description: "Version tag in format: 1.0.0 (no v prefix!) or commit sha"
        required: true

jobs:
  permissions:
    runs-on: ubuntu-latest
    name: Send not allowed message
    steps:
      - name: Not allowed to run
        if: ${{ env.GITHUB_REPOSITORY_OWNER_ID != env.GITHUB_ACTOR_ID }}
        run: |
          echo "::error::The actor ${GITHUB_ACTOR_ID} is not allowed to run the deployments"
          exit 1

  trigger:
    needs: [permissions]
    uses: ./.github/workflows/heroku.yml
    secrets: inherit
    with:
      version: v${{ inputs.version }}
      servers: '["${{ inputs.server }}"]'

  post-trigger:
    name: Print the summary
    needs: [trigger]
    runs-on: ubuntu-latest
    steps:
      - name: Summary
        run: |
          echo "Deployed a new service version: âœ¨ ${{ inputs.version }} âœ¨to ${{ inputs.server }} ðŸš€" > $GITHUB_STEP_SUMMARY
