name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      server:
        type: choice
        options:
          - "Production Ω"
          - "Production β"
        description: "What server to deploy the application on"
        required: true
      version:
        type: string
        description: "Version tag X.X.X"
        required: true

jobs:
  permissions:
    runs-on: ubuntu-latest
    name: Send not allowed message
    steps:
      - name: Not allowed to run
        if: ${{ env.GITHUB_REPOSITORY_OWNER_ID != env.GITHUB_ACTOR_ID }}
        run: |
          echo "::error::The actor ${GITHUB_ACTOR_ID} is not allowed to run the deployments"
          exit 1

  trigger:
    needs: [permissions]
    uses: ./.github/workflows/heroku.yml
    secrets: inherit
    with:
      version: ${{ inputs.version }}
      servers: '["${{ inputs.server }}"]'
