name: App Deploy

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Push docker image
    steps:
      - name: App version
        run: echo "Picked the app version ${GITHUB_SHA}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS and NPM modules
        uses: ./.github/actions/npm

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish to Registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ secrets.DOCKER_USERNAME }}/voice-to-text-bot/voice-to-speech-app:latest
            ghcr.io/${{ secrets.DOCKER_USERNAME }}/voice-to-text-bot/voice-to-speech-app:${{ github.sha }}
          build-args: APP_VERSION=${{ github.sha }}

  heroku:
    runs-on: ubuntu-latest
    name: Deploy to Heroku
    environment: ${{ matrix.environment }}
    strategy:
      max-parallel: 1
      matrix:
        environment: ["Production β", "Production Ω"]
    steps:
      - name: App version
        run: echo "Picked the app version ${GITHUB_SHA}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS and NPM modules
        uses: ./.github/actions/npm

      - name: Login to Heroku Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.heroku.com
          username: ${{ secrets.HEROKU_EMAIL }}
          password: ${{ secrets.HEROKU_API_KEY }}

      - name: Push docker image
        run: heroku container:push web --app ${{ vars.HEROKU_APP }} --arg APP_VERSION=${{ env.D_VERSION }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          D_VERSION: ${{ github.sha }}

      - name: Release docker image
        run: heroku container:release web --app ${{ vars.HEROKU_APP }}
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

  production:
    runs-on: ubuntu-latest
    name: Deploy to Railway.app production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS and NPM modules
        uses: ./.github/actions/npm

      - name: Install Railway CLI
        run: npm i -g @railway/cli
#      - name: Deploy Dockerfile to PRODUCTION
#        run: railway up
#        env:
#          RAILWAY_TOKEN: ${{ secrets.RAILWAY_PRODUCTION_TOKEN }}
