name: App Deploy

on:
  workflow_call:
    inputs:
      servers:
        type: string
        description: "The JSON list of servers to deploy the application"
        default: '["Production β", "Production Ω"]'
        # Will deploy into all available servers if not specified
        required: false
      version:
        type: string
        description: "Version tag"
        required: true
      sha:
        type: string
        description: "Commit sha"
        required: true

env:
  DEPLOY_VERSION_TAG: "v${{ inputs.version }}"

jobs:
  deploy:
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      docker-tag: latest
      version: ${{ inputs.version }}
      sha: ${{ inputs.sha }}

  heroku:
    uses: ./.github/workflows/heroku.yml
    secrets: inherit
    with:
      version: ${{ env.DEPLOY_VERSION_TAG }}
      servers: ${{ inputs.servers }}
