name: Build docker image

on:
  workflow_call:
    inputs:
      tags:
        description: "Comma or newline separated list of tags"
        required: true
        type: string
      version:
        type: string
        description: "Version tag"
        required: true
      sha:
        type: string
        default: "Commit sha"
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Push docker image
    timeout-minutes: 10
    env:
      CONTAINER_NAME: voice-to-speech-app
      CONTAINER_REGISTRY: ghcr.io
      APP_VERSION_SHA: ${{ inputs.sha }}
    steps:
      - name: App version
        run: echo "Picked the app version $APP_VERSION_SHA"

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.sha }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      #      - name: Install Python
      #        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      #        with:
      #          python-version: "3.12"

      #      Probably dont need anymore
      #      - name: Download AI model
      #        run: pip install gdown && gdown ${{ secrets.WHISPER_MODEL_URL }} -O ./model-cache

      - name: Login to GitHub Container Registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Calculate docker tags
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        env:
          CONTAINER_PATH: ${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}/${{ env.CONTAINER_NAME }}
        with:
          images: ${{ env.CONTAINER_PATH }}
          tags: ${{ inputs.tags }}

      - name: Publish to Registry
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: APP_VERSION=${{ inputs.version }}

      - name: Add image reference
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          COMMIT_SHA: ${{ inputs.sha }}
          PRIMARY_TAG: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
        with:
          script: |
            const { COMMIT_SHA: sha, PRIMARY_TAG: tag, CONTAINER_NAME: container } = process.env
            const { owner, repo } = context.repo;
            const target_url = `https://github.com/${owner}/${repo}/pkgs/container/${encodeURIComponent(`${repo}/${container}`)}`
            const description = `${container}:${tag.split(':').pop()}`;
            const api = `/repos/${owner}/${repo}/statuses/${sha}`;

            await github.request(`POST ${api}`, {
              owner,
              repo,
              sha,
              target_url,
              state: 'success',
              description,
              context: 'Docker image'
            });
