name: App Release

on:
  push:
    branches: [master]

jobs:
  tag-release:
    runs-on: ubuntu-latest
    name: Tag released changes
    steps:
      - name: App version
        run: echo "Picked the app version ${GITHUB_SHA}"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS using the obtained nvm version
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Run semantic release
        run: npx semantic-release@19.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
